pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "darshiniag/exp4"
        DOCKER_TAG = "latest"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/darshiniag/docker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(
                        "${DOCKER_IMAGE}:${DOCKER_TAG}",
                        "./Desktop/exp4"
                    )
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry(
                        'https://index.docker.io/latest/',
                        'dockerhub-credss'
                    ) {
                        docker.image(
                            "${DOCKER_IMAGE}:${DOCKER_TAG}"
                        ).push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Image successfully built and pushed to Docker Hub"
            echo "Image: ${DOCKER_IMAGE}:${DOCKER_TAG}"
        }

        failure {
            echo "Pipeline failed"
        }
    }
}
